# Generated by Django 4.0.6 on 2022-08-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosdetailing',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos_imagenes'),
        ),
    ]
