# Generated by Django 4.0.6 on 2022-08-31 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productosdetailing_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosdetailing',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
