# Generated by Django 4.0.6 on 2022-08-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_productoslimpieza'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosLimpieza',
        ),
        migrations.AlterField(
            model_name='productosdetailing',
            name='tipo',
            field=models.CharField(default='Detailing', max_length=20),
        ),
    ]
