# Generated by Django 4.0.6 on 2022-08-31 23:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_productosdetailing_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosdetailing',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
