# Generated by Django 4.0.6 on 2022-08-31 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productosdetailing_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productosdetailing',
            name='descuento',
        ),
    ]
