# Generated by Django 4.0.6 on 2022-08-31 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
