# Generated by Django 4.0.6 on 2022-09-01 23:38

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0003_delete_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_contacto', models.CharField(choices=[('VENDEDOR', 'Quiero ser vendedor'), ('COMPRA', 'Quiero comprar')], default='VENDEDOR', max_length=20)),
                ('contenido', ckeditor.fields.RichTextField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
