# Generated by Django 4.0.6 on 2022-08-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.IntegerField(max_length=30)),
                ('turno', models.DateField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
